### ISSUE TITLE
Проверка на тип по ID

### ISSUE THREAD

**Issue by IMrProYTI** [te9c/jellyfin-shikimori-plugin#1]
## Что должно происходить:

Строка проходит регулярное выражение и никак его в итоге не изменяет.
И исправно вносит метаданные куда нужно :)

## Что происходит на самом деле:

Код падает с ошибкой `error CS0103: The name 'Regex' does not exist in the current context` из за парсинга не существующих тегов (такое поведения наблюдается с [данным аниме](https://shikimori.one/animes/48171))

## Код воспроизведения ошибки:
**Место ошибки в коде:**
+ [Функция](https://github.com/te9c/jellyfin-shikimori-plugin/blob/c8b4c721dd2554dbee76348b8dd788556f22fae4/Jellyfin.Plugin.Shikimori/Api/ApiModel.cs#L207)
+ [Место вызова функции](https://github.com/te9c/jellyfin-shikimori-plugin/blob/c8b4c721dd2554dbee76348b8dd788556f22fae4/Jellyfin.Plugin.Shikimori/Api/ApiModel.cs#L220)

## Минимальный код для повторения данной ошибки
*(используя внутренный код плагина)*
```cs
using System;

public class JellyfinShikimoriPlugin
{
    public static void Main(string[] args)
    {
        string description = "Вы когда-нибудь слышали о летнем призраке? Согласно городской легенде, призрак молодой девушки появляется, когда в небо запускают салют...";
        Console.WriteLine(DeleteTagsInText(description));
    }
    
    private string DeleteTagsInText(string text) {
        text = Regex.Replace(text, @"\[.*?\]", "");
        text = Regex.Replace(text, @" ([.,;: ])", "$1");
        
        return text;
    }
}
```

## Вероятное и самое простое решение:
Обернуть регулярные выражения в `try` `catch` и при ошибке возвращать строку без изменений.

**Comment by te9c** [comment]
Класс `Regex` объявлён в пространстве имён `System.Text.RegularExpressions`, и, чтобы исправить ошибку в приведённом случае, необходимо добавить `using System.Text.RegularExpressions`. Но вообще [`Regex.Replace`](https://learn.microsoft.com/en-us/dotnet/api/system.text.regularexpressions.regex.replace?view=net-8.0) не выдаёт исключение, если не находит паттерн.

**Comment by te9c** [comment]
По поводу [этого аниме](https://shikimori.one/animes/48171) на последней версии плагина `3.2.0.0` я не наблюдаю ошибки при загрузке метаданных.

**Comment by IMrProYTI** [comment]
## Версии:
Jellyfin: `10.9.4` `stable`
Shiki плагина: `3.2.0.0`
![изображение](https://github.com/te9c/jellyfin-shikimori-plugin/assets/58055542/1f4f9d1e-0955-4957-a7bf-8509f9c289ec)
![изображение](https://github.com/te9c/jellyfin-shikimori-plugin/assets/58055542/ec350582-840f-46d7-9729-ca7a8e6c56a7)

## Ошибка Regex.Replace:
При распознавании именно конкретно данного аниме результаты поиска пустые, а тот "минимальный код", всё же выдаёт ошибку, ошибка явно возникает в первом попавшемся онлайн компиляторе: https://www.onlinegdb.com/online_csharp_compiler
![изображение](https://github.com/te9c/jellyfin-shikimori-plugin/assets/58055542/4b36677b-8e6e-4922-8d45-3d9b3ce0bb46)

## Не возможность загрузки
1. Создал категорию только с одним загрузчиком метаданных
2. Попробоввал одно аниме к загрузке
3. Попробовал другое

Вывод: Одно находится, второе нет (так не должно быть)

Видео с примером: https://youtu.be/jpsIhXMOA5M

## Post Scriptum
Я могу быть не компетентен в данном вопросе, по скольку на C# я программировал не так много. Надеюсь в таком случае на помощь :)

**Comment by IMrProYTI** [comment]
> Класс `Regex` объявлён в пространстве имён `System.Text.RegularExpressions`, и, чтобы исправить ошибку в приведённом случае, необходимо добавить `using System.Text.RegularExpressions`. Но вообще [`Regex.Replace`](https://learn.microsoft.com/en-us/dotnet/api/system.text.regularexpressions.regex.replace?view=net-8.0) не выдаёт исключение, если не находит паттерн.

Да, здесь именно я ошибся /ᐠ｡ꞈ｡ᐟ\

**Comment by te9c** [comment]
В видео ты создаешь медиатеку с типом "Телешоу" (т.е. сериалы), но "Летний призрак" - это фильм. Плагин ищет сериал с названием "Летний призрак", но не находит его.

# Варианты решения
 1. Создать две отдельные медиатеки - аниме фильмы (с типом "Фильмы") и аниме сериалы (с типом "Телешоу").
 2. Создать медиатеку с типом "Смешанные фильмы и передачи", но для ее нормальной работы необходимо следовать правилам названия [сериалов](https://jellyfin.org/docs/general/server/media/shows/) и [фильмов](https://jellyfin.org/docs/general/server/media/movies) в Jellyfin'е. Хотя там вроде можно и вручную указать фильмы и сериалы через диспетчер метадаты.
<img width="835" alt="Screenshot 2024-06-17 at 19 04 15" src="https://github.com/te9c/jellyfin-shikimori-plugin/assets/47248306/a8ff185e-a98d-4ab6-be37-10447dcbee34">

**Comment by te9c** [comment]
Вообще, наверное, стоит убрать проверку на тип аниме, при идентификации через `ID`.

**Comment by IMrProYTI** [comment]
> В видео ты создаешь медиатеку с типом "Телешоу" (т.е. сериалы), но "Летний призрак" - это фильм. Плагин ищет **сериал** с ID `48171`, но не находит его.
> # Варианты решения
> 
>     1. Создать две отдельные медиатеки - аниме фильмы (с типом "Фильмы") и аниме сериалы (с типом "Телешоу").
> 
>     2. Создать медиатеку с типом "Смешанные фильмы и передачи", но для ее нормальной работы необходимо следовать правилам названия [сериалов](https://jellyfin.org/docs/general/server/media/shows/) и [фильмов](https://jellyfin.org/docs/general/server/media/movies) в Jellyfin'е. Хотя там вроде можно и вручную указать фильмы и сериалы через диспетчер метадаты.
>

Я добавлял различные Аниме/ТВ сериалы/Фильмы и с остальными всё работало. Да я знаю про существование Отдельных разделов (настроек) каталогов и в них. Уверяю, они настроены верно точь-в-точь твоим словам.

Обычно при определённом каталоге ID который ведёт на Shiki должен в таком случае вести в никуда, но заполнит мету вручную и воспользовавшись определённой кнопочкой правее от ввода ID (А так же на главной странице) он ведёт куда нужно, то есть определяет, что Аниме, что Фильм нормально.

Используя другие сервисы (например AniDB или КиноПоиск) выше приоритетом, всё находится спокойно

Пример с КиноПоиском (откуда и подтянулись другие метаданные фильма), где подтянулось описание:
![image](https://github.com/te9c/jellyfin-shikimori-plugin/assets/58055542/5063cf91-d59f-4a03-9a87-73de3b046a84)

**Comment by IMrProYTI** [comment]
> > В видео ты создаешь медиатеку с типом "Телешоу" (т.е. сериалы), но "Летний призрак" - это фильм. Плагин ищет **сериал** с ID `48171`, но не находит его.
> > # Варианты решения
> > ```
> > 1. Создать две отдельные медиатеки - аниме фильмы (с типом "Фильмы") и аниме сериалы (с типом "Телешоу").
> > 
> > 2. Создать медиатеку с типом "Смешанные фильмы и передачи", но для ее нормальной работы необходимо следовать правилам названия [сериалов](https://jellyfin.org/docs/general/server/media/shows/) и [фильмов](https://jellyfin.org/docs/general/server/media/movies) в Jellyfin'е. Хотя там вроде можно и вручную указать фильмы и сериалы через диспетчер метадаты.
> > ```
> 
> Я добавлял различные Аниме/ТВ сериалы/Фильмы и с остальными всё работало. Да я знаю про существование Отдельных разделов (настроек) каталогов и в них. Уверяю, они настроены верно точь-в-точь твоим словам.
> 
> Обычно при определённом каталоге ID который ведёт на Shiki должен в таком случае вести в никуда, но заполнит мету вручную и воспользовавшись определённой кнопочкой правее от ввода ID (А так же на главной странице) он ведёт куда нужно, то есть определяет, что Аниме, что Фильм нормально.
> 
> Используя другие сервисы (например AniDB или КиноПоиск) выше приоритетом, всё находится спокойно
> 
> Пример с КиноПоиском (откуда и подтянулись другие метаданные фильма), где подтянулось описание и рейтинг: ![image](https://private-user-images.githubusercontent.com/58055542/340348178-5063cf91-d59f-4a03-9a87-73de3b046a84.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg2Mzc1ODIsIm5iZiI6MTcxODYzNzI4MiwicGF0aCI6Ii81ODA1NTU0Mi8zNDAzNDgxNzgtNTA2M2NmOTEtZDU5Zi00YTAzLTlhODctNzNkZTNiMDQ2YTg0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE3VDE1MTQ0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYxYjk3Yzk1MzU2Mzk0OGRiN2I3YjFmYjY1NzZkY2ZkNjczMmMwYmViNGIzNjY2ZmFmNzQ4ODBlMDQyMmQ0OTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PXXMuvhaqd4PGKB3jOWQR0WxtCG3szYMzUBfXZ7dPVM)

Мгновенно говорю, что КиноПоиск стоит в приоритете ниже Shiki в загрузке метаданных

**Comment by te9c** [comment]
Вот сейчас плагин должен в любом случае подгружать информацию, если ему скормить idшник. Ты можешь забилдить плагин с последнего комита и протестировать перед тем как я релизну его?

**Comment by IMrProYTI** [comment]
> Вот сейчас плагин должен в любом случае подгружать информацию, если ему скормить idшник. Ты можешь забилдить плагин с последнего комита и протестировать перед тем как я релизну его?

Теперь всё работает как часы! Спасибо за время потраченное на меня 😅 Надеюсь хоть в чём-то помог...
Под корректируй название issue. Заливай изменения. И закрывай его (✿◕‿◕✿) Ну или ещё чего.

**Comment by te9c** [comment]
Все, теперь можно обновить плагин через джелифиновский каталог. Спасибо за помощь в обнаружении двух проблем :)
