### ISSUE TITLE
Update the plugin to version jf 10.10.0

### ISSUE THREAD

**Issue by Druidblack** [te9c/jellyfin-shikimori-plugin#2]
Good afternoon. Update the plugin to work with jf 10.10.0

**Comment by te9c** [comment]
Hi, is there something that not working? The plugin seems to work fine with jellyfin 10.10.0

**Comment by Druidblack** [comment]
Добрый день. Честно говоря еще не обновлялся до 10.10.0. Ждал пока все плагины обновят до 10 версии. 
Я в манифесте посмотрел, стоит версия "targetAbi": "10.9.0". Поэтому и написал. Если все работает то хорошо. Можно тогда обновляться.

**Comment by te9c** [comment]
Привет, плагин теперь обновлён до последнией версии.
